# Funding options for GitHub Sponsors
# Uncomment and customize as needed

# github: [yourusername]
# patreon: yourusername
# ko_fi: yourusername
# custom: ['https://buymeacoffee.com/yourusername']

# For now, show a message to interested contributors:
# "Love AI Dungeon Master? Star the repo and tell your D&D friends!"
